version: '3'

services:
  postgresqldb:
    container_name: postgresqldb
    image: postgres:latest
    environment:
      POSTGRES_DB: devops
      POSTGRES_PASSWORD: superStrongP@ss
      POSTGRES_USER: postgres
    restart: always
    ports:
      - 5555:5432
  api: 
    container_name: api
    image: yassine15/demo-app:spring-app-1.0
    depends_on:
      - postgresqldb
    ports:
      - 8080:8080
    restart: always

volumes:
  pgdata:
